# Site settings
title: Gaussian Process Workshop on Spatio-Temporal Modelling, 2014
email: 
description: > # this means to ignore newlines until "baseurl:"
  The 2014 Gaussian Process Workshop on Spatio-Temporal Modelling held at the University of Sheffield.
baseurl: "/gpst14" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

youtube:
  height: 315
  width: 560

conference:
  hosts:
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  #  - {name: Javier Gonzalez, url: "http://javiergonzalezh.github.io/"}
  #  - {name: Zhenwen Dai, url: "http://staffwww.dcs.shef.ac.uk/people/Z.Dai/"}
  #  - {name: Sheffield ML Group, url: "http://sheffieldml.github.io"}
  name: Gaussian Process Summer School
  location: University of Sheffield, UK
  year: 2014
  month: January
  # add other days here for them to appear
  dates:	
  - {date: 16, day: Thursday, month: January, year: 2014}
  
# Build settings
markdown: kramdown

